import { StyleSheet } from "react-native";
import { colors } from "../../constants/theme";
import {
  HEADER_HEIGHT,
  ROW_HEIGHT,
  ROW_GAP,
  TASK_NAME_WIDTH,
  BAR_RADIUS,
  DASH_SIZE,
  DASH_GAP,
} from "./constants";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F3F4F6",
    borderRadius: 0,
    borderWidth: 0,
    overflow: "visible",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 2.5,
    borderColor: "#111",
    backgroundColor: "#FFEFD5",
  },
  title: {
    fontSize: 18,
    fontWeight: "900",
    color: colors.text,
    flexShrink: 1,
    marginRight: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  switcherWrap: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 0,
    padding: 4,
    borderWidth: 2.5,
    borderColor: "#111",
  },
  switcherWrapFloating: {
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.5)",
    borderRadius: 0,
    padding: 3,
    borderWidth: 2,
    borderColor: "#111",
  },
  switcherPill: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 0,
  },
  switcherPillFloating: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 0,
  },
  switcherPillActive: {
    backgroundColor: "#111",
  },
  switcherText: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  switcherTextFloating: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  switcherTextActive: {
    color: "#fff",
  },
  switcherFloatTop: {
    position: "absolute",
    top: HEADER_HEIGHT + 12,
    right: 8,
    zIndex: 20,
  },
  floatButtons: {
    position: "absolute",
    bottom: 12,
    right: 8,
    zIndex: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  floatButton: {
    width: 40,
    height: 40,
    borderRadius: 0,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2.5,
    borderColor: "#111",
  },
  floatButtonWide: {
    width: "auto",
    minWidth: 48,
    paddingHorizontal: 10,
  },
  floatButtonText: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.text,
  },
  floatButtonTextSmall: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.text,
  },
  body: {
    flexDirection: "row",
  },
  leftPanel: {
    width: TASK_NAME_WIDTH,
    borderRightWidth: 2,
    borderRightColor: "#111",
    backgroundColor: "#E5E7EB",
  },
  leftHeaderSpacer: {
    borderBottomWidth: 2,
    borderBottomColor: "#111",
  },
  taskNameRow: {
    height: ROW_HEIGHT,
    marginTop: ROW_GAP,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  taskNameText: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.text,
    opacity: 0.9,
    textTransform: "uppercase",
  },
  rightPanel: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  timelineHeaderRow: {
    height: HEADER_HEIGHT,
    flexDirection: "row",
    alignItems: "flex-end",
    borderBottomWidth: 2,
    borderBottomColor: "#111",
    position: "relative",
    backgroundColor: "#FEF3C7",
  },
  headerCell: {
    alignItems: "center",
    justifyContent: "flex-end",
    paddingBottom: 6,
  },
  headerCellWeek: {
    borderLeftWidth: 2,
    borderLeftColor: "#111",
    alignItems: "flex-start",
    paddingLeft: 6,
  },
  headerCellMonth: {
    borderLeftWidth: 2,
    borderLeftColor: "#111",
    alignItems: "flex-start",
    paddingLeft: 6,
  },
  headerDayText: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.textSecondary,
    textTransform: "uppercase",
  },
  headerMonthText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.text,
    opacity: 0.8,
    textTransform: "uppercase",
  },
  gridLine: {
    position: "absolute",
    top: 0,
    width: 2,
    backgroundColor: "#D1D5DB",
    opacity: 1,
  },
  barsContainer: {
    position: "relative",
  },
  taskBar: {
    position: "absolute",
    borderRadius: 0,
    borderWidth: 2.5,
    borderColor: "#111",
    backgroundColor: "#A5B4FC",
  },
  todayLineContainer: {
    position: "absolute",
    top: -HEADER_HEIGHT,
    alignItems: "center",
    width: 2,
    zIndex: 10,
  },
  dashedLineWrap: {
    alignItems: "center",
    flex: 1,
  },
  todayLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.accent,
    marginBottom: 4,
    textTransform: "uppercase",
  },
  dash: {
    width: 2,
    height: DASH_SIZE,
    backgroundColor: colors.accent,
    marginBottom: DASH_GAP,
    borderRadius: 0,
  },
});
